stages:
  - build
  - test
  - deploy


build_job:
  image: maven:latest
  stage: build
  script:
    - mvn compile

test_job:
  image: maven:latest
  stage: test
  script:
    - mvn test -e

deploy_job:
  stage: deploy
  image: ruby:latest
  script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl
  - dpl --provider=heroku --app=mediador-pedagogico --api-key=48baed2e-c7f2-4548-a5d0-e5942e2fd729
  only:
    - develop